### ISSUE TITLE
Binario

### ISSUE THREAD

**Issue by LuigiVessella** [LuigiVessella/iterazione_c#11]
prof io ho problemi con questo esercizio..In particolare quando il numero in binario inizia con 0..
Ad esempio 01011, in quanto non riesco a scomporlo in singole cifre

**Comment by LuigiVessella** [comment]
Apposto prof avevo sbagliato delle condizioni di controllo ora funziona..

**Comment by FabioZTessitore** [comment]
Ok

Il 25 mag 2017 10:13 AM, "LuigiVessella" <notifications@github.com> ha
scritto:

**Comment by LuigiVessella** [comment]
Fatto, caricato.

**Comment by FabioZTessitore** [comment]
È inutilmente complicato. Devi rivedere un po' la logica

**Comment by LuigiVessella** [comment]
Ok prof io controllo, intanto ho caricato cripta/decripta

**Comment by LuigiVessella** [comment]
prof io sto caricando

**Comment by FabioZTessitore** [comment]
manca la parte di conversione in decimale

**Comment by FabioZTessitore** [comment]
correzione: il codice è tutto da rivedere

**Comment by LuigiVessella** [comment]
Prof sto ricominciando con il laboratorio...Ho semplificato binario ma non considerate la parte del controllo..

**Comment by LuigiVessella** [comment]
Prof dopo un'ora di ragionamento ci sono arrivato e adesso è completamente funzionante e comprensibile.
