### ISSUE TITLE
makefile

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/iterazione_c#12]
perché non c'è un makefile?

**Comment by LuigiVessella** [comment]
perchè non l'ho mai creato

**Comment by LuigiVessella** [comment]
fatto

**Comment by FabioZTessitore** [comment]
c'è un errore (anche se al momento non importante). Non è LDFLAGS, ma LDLIBS

**Comment by LuigiVessella** [comment]
Avevo sbagliato a scrivere
