### ISSUE TITLE
pigreco

### ISSUE THREAD

**Issue by LuigiVessella** [LuigiVessella/iterazione_c#14]
Ho fatto anche pigreco..Dopo averlo fatto ho dato uno sguardo alla soluzione ed è abbastanza diversa dal mio..però sembra funzionare

**Comment by FabioZTessitore** [comment]
prova a non usare l'if per decidere se sommare o sottrarre

**Comment by LuigiVessella** [comment]
Anche qui ho fatto

**Comment by FabioZTessitore** [comment]
togliere if

**Comment by LuigiVessella** [comment]
fatto

**Comment by FabioZTessitore** [comment]
Va bene. Se ti va puoi eliminare la variabile pig
