### ISSUE TITLE
summvett

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/iterazione_c#16]
usa double invece di float

perché il vettore è di 100 elementi?

**Comment by LuigiVessella** [comment]
Prof ho un problema con double cioè che con lo specificatore double %lf mi dice che lo standard iso c90 non lo supporta, se uso %f mi dice che non va bene per double..Che metto?

**Comment by LuigiVessella** [comment]
Pure questo

**Comment by LuigiVessella** [comment]
Ho fatto gli aggiustamenti
