### ISSUE TITLE
countdown

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/iterazione_c#2]
Aggiusta il modo in cui è scritto il codice (spazi, a capo, righe vuote, ecc)

Poi fai in modo che il conteggio inizi dal numero inserito

**Comment by LuigiVessella** [comment]
agli ordini capo

**Comment by LuigiVessella** [comment]
fatto

**Comment by FabioZTessitore** [comment]
puoi aggiustare le spaziature in modo decente? se non sai come fare dillo, ma non dire che hai fatto se non è vero

**Comment by LuigiVessella** [comment]
Prof voi chiedete troppo ahah..
Perché esiste pure il modo di mettere gli spazi?😂
Non so come si fa allora

Il 10 apr 2017 21:09, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
questo lo aggiusto io, gli altri fai tu
