### ISSUE TITLE
tabellina(pitagorica)

### ISSUE THREAD

**Issue by LuigiVessella** [LuigiVessella/iterazione_c#3]
Prof ho problemi a stamparla sulla stessa riga in quanto non mi mette gli spazi..come in c++ facessi:
cout<< "    "<<num;

**Comment by FabioZTessitore** [comment]
la tabella pitagorica non si fa così

**Comment by LuigiVessella** [comment]
Ma l'esercizio non l'ho caricato, quello era una bozza che si è caricata
perché ho fatto git add .

Il 10 apr 2017 21:17, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LuigiVessella** [comment]
Mi serve sapere come si fanno gli spazi però

Il 10 apr 2017 21:32, "Luigi Vessella" <vessellaluigi12@gmail.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Non capisco, hai fatto un sacco di esercizi con stampe di tutti i tipi e ora non sai mettere degli spazi?

**Comment by LuigiVessella** [comment]
Io ricordo /t...

Il 10 apr 2017 9:35 PM, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LuigiVessella** [comment]
Si prof mi ricordavo bene \t ...
Penso di caricarlo domani
