### ISSUE TITLE
tabelline

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/iterazione_c#5]
in attesa

**Comment by LuigiVessella** [comment]
Buona pasqua prof

Il 14 apr 2017 11:27 AM, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Ricambio

Il 16 apr 2017 8:21 AM, "LuigiVessella" <notifications@github.com> ha
scritto:

**Comment by LuigiVessella** [comment]
Ho caricato

**Comment by LuigiVessella** [comment]
Ho caricato anche massimo

**Comment by FabioZTessitore** [comment]
Quando si stampa la tabella pitagorica si dovrebbero vedere le tabelline dall'uno al dieci

**Comment by LuigiVessella** [comment]
si "DOVREBBERO "

**Comment by LuigiVessella** [comment]
Fatto
