### ISSUE TITLE
due maggiori

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/iterazione_c#7]
hai provato ad eseguire, cosa esce?

**Comment by LuigiVessella** [comment]
Ho iniziato a caricare il do while, questo dei due maggiori lo vedrò più in la

**Comment by FabioZTessitore** [comment]
aggiusta

**Comment by LuigiVessella** [comment]
Ora pare che funziona prof

**Comment by FabioZTessitore** [comment]
non è vero

**Comment by LuigiVessella** [comment]
Ma come no

**Comment by FabioZTessitore** [comment]
prova ad inserire tutti numeri negativi

**Comment by LuigiVessella** [comment]
ora dovrebbe andare pt.2

**Comment by LuigiVessella** [comment]
prof io ho caricato
