### ISSUE TITLE
quadrato

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/iterazione_c#8]
perché chiedi di inserire il lato del quadrato?

**Comment by LuigiVessella** [comment]
Intesa come numero di asterisci ahah

**Comment by FabioZTessitore** [comment]
Ripeto la domanda: perché chiedi di inserire il lato del quadrato?

**Comment by LuigiVessella** [comment]
Perchè lo dobbiamo dire noi il numero di asterischi

**Comment by LuigiVessella** [comment]
mo ho cambiato nel file

**Comment by FabioZTessitore** [comment]
Questo numero che ti fai dare non lo usi da nessuna parte

**Comment by LuigiVessella** [comment]
Ahhh oddio ahahah..Scusate prof...Ho corretto
