### ISSUE TITLE
Occorrenze cifra

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/iterazione_c#9]
Non funziona

**Comment by LuigiVessella** [comment]
In quale caso non funziona? se io inserisco 1978 mi dice 1

**Comment by LuigiVessella** [comment]
e se inserisco 7777 dice 4

**Comment by LuigiVessella** [comment]
forse ho trovato l'errore, ora ricarico

**Comment by FabioZTessitore** [comment]
Ora va bene. Mi spieghi a che serve la variabile i?

**Comment by LuigiVessella** [comment]
In effetti potrei controllare direttamente modulo..per fare con ordine ho messo una variabile..
Ma è inutile in sostanza
